import re
from playwright.sync_api import Playwright, sync_playwright, expect


def test_register(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://rahulshettyacademy.com/client/#/auth/login")
    page.get_by_text("Register here").click()
    page.get_by_role("textbox", name="First Name").click()
    page.get_by_role("textbox", name="First Name").fill("Mahashakti")
    page.get_by_role("textbox", name="Last Name").click()
    page.get_by_role("textbox", name="Last Name").fill("Sahinayak")
    page.get_by_role("textbox", name="email@example.com").click()
    page.get_by_role("textbox", name="email@example.com").fill("sonu@gmail.com")
    page.get_by_role("textbox", name="enter your number").click()
    page.get_by_role("textbox", name="enter your number").fill("9861210540")
    page.get_by_role("combobox").select_option("3: Engineer")
    page.get_by_role("radio", name="Male", exact=True).check()
    page.get_by_role("textbox", name="Passsword").click()
    page.get_by_role("textbox", name="Passsword").fill("11021998")
    page.get_by_role("textbox", name="Confirm Password").click()
    page.get_by_role("textbox", name="Confirm Password").fill("11021998")
    page.get_by_role("checkbox").check()
    page.get_by_role("button", name="Register").click()
    page.get_by_role("button", name="Register").click()
    page.get_by_role("textbox", name="Passsword").dblclick()
    page.get_by_role("textbox", name="Passsword").fill("Sonusanu@1")
    page.get_by_role("textbox", name="Confirm Password").dblclick()
    page.get_by_role("textbox", name="Confirm Password").fill("Sonusanu@1")
    page.get_by_role("button", name="Register").click()
    page.get_by_role("textbox", name="email@example.com").click()
    page.get_by_role("textbox", name="email@example.com").click()
    page.get_by_role("textbox", name="email@example.com").press("ArrowLeft")
    page.get_by_role("textbox", name="email@example.com").press("ArrowLeft")
    page.get_by_role("textbox", name="email@example.com").press("ArrowLeft")
    page.get_by_role("textbox", name="email@example.com").press("ArrowLeft")
    page.get_by_role("textbox", name="email@example.com").press("ArrowLeft")
    page.get_by_role("textbox", name="email@example.com").press("ArrowLeft")
    page.get_by_role("textbox", name="email@example.com").press("ArrowLeft")
    page.get_by_role("textbox", name="email@example.com").press("ArrowLeft")
    page.get_by_role("textbox", name="email@example.com").press("ArrowRight")
    page.get_by_role("textbox", name="email@example.com").fill("mahashakti@gmail.com")
    page.get_by_role("button", name="Register").click()
    page.get_by_role("button", name="Login").click()
    page.get_by_role("textbox", name="email@example.com").click()
    page.get_by_role("textbox", name="email@example.com").fill("mahashakti@gmail.com")
    page.get_by_role("textbox", name="enter your passsword").click()
    page.get_by_role("textbox", name="enter your passsword").fill("Sonusanu@1")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("button", name=" Add To Cart").first.click()
    page.get_by_role("button", name="   Cart").click()
    page.get_by_role("button", name="Checkout❯").click()
    page.get_by_role("textbox", name="Select Country").click()
    page.get_by_role("textbox", name="Select Country").fill("india")
    page.get_by_role("button", name=" India").click()
    page.get_by_text("Place Order").click()

    # ---------------------
    context.close()
    browser.close()



def test_login(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://rahulshettyacademy.com/client/#/auth/login")
    page.get_by_role("textbox", name="email@example.com").click()
    page.get_by_role("textbox", name="email@example.com").fill("mahashakti@gmail.com")
    page.get_by_role("textbox", name="enter your passsword").click()
    page.get_by_role("textbox", name="enter your passsword").fill("Sonusanu@1")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("button", name=" Add To Cart").first.click()
    page.get_by_role("button", name="   Cart").click()
    page.get_by_role("button", name="Checkout❯").click()
    page.get_by_role("textbox", name="Select Country").click()
    page.get_by_role("textbox", name="Select Country").fill("india")
    page.get_by_role("button", name=" India").click()
    page.get_by_text("Place Order").click()
    page.get_by_role("textbox", name="email@example.com").click()
    page.get_by_role("textbox", name="email@example.com").fill("mahashakti@gmail.com")
    page.get_by_role("textbox", name="enter your passsword").click()
    page.get_by_role("textbox", name="enter your passsword").fill("Sonusanu@1")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("button", name=" Add To Cart").nth(1).click()
    page.get_by_role("button", name="   Cart").click()
    page.get_by_role("button", name="Checkout❯").click()
    page.get_by_role("textbox", name="Select Country").click()
    page.get_by_role("textbox", name="Select Country").fill("india")
    page.get_by_role("button", name=" India").click()
    page.get_by_text("Place Order").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    test_login(playwright)


